### PR TITLE
Changed urls & added a banner that links to new website

### PR DESCRIPTION
**Pull request by alanvww**
Fixed docs urls to use `archive-docs.ml5js.org` and added banner link to the new website. 
Preview deployment: https://ml5-website-archive.netlify.app/

@MOQN @shiffman Successfully built and ran the project locally. However, deployment on Netlify can still be tricky. The current preview is based on the built folder I uploaded.

### CODE REVIEW

**Comment by alanvww** [comment]
Of course the preview deployment triggered by PR will fail... I will dive deeper into what is going on with Netlify, it also failed on my end :( 

And I had also separated the `docs` in ml5-library into a new repo: https://github.com/ml5js/ml5-archive-docs with updated links. will work on updating the content soon, like change `ml5@latest` to `ml5@0.12.2`...etc.
Preview: https://ml5js.github.io/ml5-archive-docs/#/

**Comment by shiffman** [comment]
Banner looks great! Let me know if there's anything I can do to help in terms of the Netlify build?

**Comment by alanvww** [comment]
> Banner looks great! Let me know if there's anything I can do to help in terms of the Netlify build?

Thanks Dan! I think I figured it out :D In the Netlify build settings, try removing the "Gatsby" and leaving it as "Not Set" for the Runtime (top right corner in this screenshot).
image
Then go back to deploy, click "Clear cache and deploy site" under "trigger deploy" and it should work like a charm. The problem is that when Netlify detects that our repo is using Gatsby, it tries to use a plugin package they made called `@netlify/gatsby` and that plugin does not work with all the old dependencies we have right now. So by removing it, it should switch back to just using the regular build process like on our local machine.  

I tested this on my Netlify account and it works.

**Comment by alanvww** [comment]
Update: Removed yarn from package management because it messes things up 💢 and only use npm for now

**Comment by shiffman** [comment]
Ok, I removed `gatsby` from the build settings, going to go ahead and merge and see what happens!

**Comment by MOQN** [comment]
This is amazing! It works great on my end. Thank you @alanvww for all the work.

**Pull request merged**
