### PR TITLE
Adds demo/preview images to reference page

### PR DESCRIPTION
**Pull request by joeyklee**
Updates the reference page to include a grid of images related to the specified model. 

I'm not sure this is what we want, but I figure I would propose this as a possibility. Still some things can/need to be done:
+ maybe we can roll up those two components into 1? ModelList.js and ModelListCards.js
+ maybe also need to define a consistent style for the images? right now it is a motley blend!
+ Need to add Link A tag to image if not already.

Happy to hear thoughts and opinions on this @wenqili,  @shiffman 

Updated 2019/05/09
Screenshot_2019-05-09 ml5js·Friendly Machine Learning For The Web(3)

### CODE REVIEW

**Comment by shiffman** [comment]
I love this idea! A couple quick thoughts:

I think it would nice to organize into three categories, something like. . . .

* images, words, sounds
* image, text, sound
* pixels, characters, sounds

At some point we probably need a fourth category for multi-purpose things that you train? At the moment this is just the `FeatureExtractor` (which only works for images so can stay there fow now) and `KNNClassifier`.  I have no idea what to call this category! Any ideas?

@joeyklee would sorting into categories work with this design idea?

Also, let's use something less gender normative for word2vec, how about `cat + puppy - dog = kitten`?

**Comment by joeyklee** [comment]
> I love this idea! A couple quick thoughts:
> 
> I think it would nice to organize into three categories, something like. . . .
> 
>     * images, words, sounds
> 
>     * image, text, sound
> 
>     * pixels, characters, sounds
> 

+ Yep, these are friendly categories :)  ==> I would go for Image, Text, and Sound for now

> 
> At some point we probably need a fourth category for multi-purpose things that you train? At the moment this is just the `FeatureExtractor` (which only works for images so can stay there fow now) and `KNNClassifier`. I have no idea what to call this category! Any ideas?
> 
> @joeyklee would sorting into categories work with this design idea?

+ Yes, I think so. Each model/feature can accept `tags` in the yaml frontmatter, so I think once we tag each of the models, then we can arrange the display as such. It will take a little tweaking, but it can be done! 

> 
> Also, let's use something less gender normative for word2vec, how about `cat + puppy - dog = kitten`?

+ Yes, totally. This is great. I'll update the images. 

UPDATE: 
Screen Shot 2019-05-09 at 11 35 21

**Comment by yining1023** [comment]
> At some point we probably need a fourth category for multi-purpose things that you train? At the moment this is just the FeatureExtractor (which only works for images so can stay there fow now) and KNNClassifier. I have no idea what to call this category! Any ideas?

In the future, when we have more models, maybe we can group them further into 3 subcategories?
- image
  - pre-trained: `mobileNet`, `darkNet`, `postNet`, `YOLO`, `UNET`, `styleTransfer`, `pix2pix`, `CVAE`
  - re-train/transfer learning: `FeatureExtractor`, `KNNClassifier`
  - create & train your own model: `imageClassifier`

Or maybe just add another category called `transfer learning`? Let's talk more about it when we have more models.

**Comment by joeyklee** [comment]
For now I will merge this in and we can update/adjust as we see fit! Thanks!

**Pull request merged**
