### PR TITLE
website edits

### PR DESCRIPTION
**Pull request by shiffman**
I am going over the reference and will push edits to this branch. @joeyklee making this as WIP so that it can reviewed as I do it in bits and pieces. Will let you know when I have completed my review!

### CODE REVIEW

**Comment by joeyklee** [comment]
Super! Thanks so much @shiffman !

**Comment by shiffman** [comment]
I've run out of time for today but hope to return to reviewing more tomorrow / next week / etc. @joeyklee feel free to review / merge as you see fit and I can open a new pull request with further work. Or leave as is if you prefer to wait.

**Comment by joeyklee** [comment]
Thanks so much + will do!

**Comment by joeyklee** [comment]
Merged! Thanks @shiffman !

**Pull request merged**
